Done with the Job first page, still have a bug to fix and on first pa…
AfriSplash-Remotely/AfriSplash-SuperAdmin pull request #11
Opened 2023-04-27 23:49 UTC by Ilesanmi-Erioluwa-Victor

…ge, will start Job detail page

2023-04-28 07:56 UTC, copy-ninja1 requested changes

2023-04-28 07:56 UTC, copy-ninja1 commented on package.json
> +    "tailwindcss": "^3.3.2",
please no tailwind use chakara for everything

2023-04-28 07:56 UTC, copy-ninja1 commented on src/components/Nav/index.tsx
>      <Box {...dflex} paddingBottom="1.5rem" width="100%">
delete this component

2023-04-29 16:47 UTC, Ilesanmi-Erioluwa-Victor commented on package.json
> +    "@heroicons/react": "^2.0.17",
Okay boss, i will do that

2023-04-29 16:50 UTC, Ilesanmi-Erioluwa-Victor commented on src/components/Nav/index.tsx
>      <Box {...dflex} paddingBottom="1.5rem" width="100%">
I was not the one that worked on Nav component

2023-05-01 10:48 UTC, copy-ninja1 commented
delete the package-lock.json, allways use yarn

2023-05-02 11:13 UTC, merged