feat: added the companies screen
AfriSplash-Remotely/AfriSplash-SuperAdmin pull request #16
Opened 2023-04-28 15:42 UTC by AJcreativity001

2023-04-28 20:36 UTC, copy-ninja1 requested changes

2023-04-28 20:36 UTC, copy-ninja1 commented on src/Modules/Companies/components/card.tsx
> +      {CardData.map((c, index) => {
this component should only hold a single card, do not loop it here. the loop should be on the Companies page

2023-04-28 20:36 UTC, copy-ninja1 commented on src/Modules/Companies/components/card.tsx
> +            boxShadow="0px 4px 12px rgba(194, 194, 194, 0.2)"
```suggestion
            boxShadow="100"
```

2023-04-28 20:36 UTC, copy-ninja1 commented on src/Modules/Companies/components/header.tsx
> +      boxShadow="0px 4px 12px rgba(194, 194, 194, 0.2)"
```suggestion
      boxShadow="200"
```

2023-04-28 21:02 UTC, copy-ninja1 commented
please complete the company flow, on click of the company card a modal should come up showing you more details about the company
https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=9824-86098&t=d99B7E7SxTR84HXF-4

2023-04-29 09:06 UTC, sammy-code98 reviewed
great work  chief
just  fix the changes @copy-ninja1  pointed out

2023-04-30 11:03 UTC, copy-ninja1 approved these changes

2023-04-30 11:03 UTC, merged